import Head from "next/head";
import { Fragment } from "react";
import Sidebar from "./sidebar/Sidebar";

const Layout = ({ children }) => {
  return (
    <Fragment>
      <Head>
        <title>Side-Bar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
      </Head>

      <div className="main-content">
        <header className="header">
          <span>Side Bar</span>
        </header>
        <Sidebar />
        <main className="main">{children}</main>

        <footer className="footer">
          <a href="https://github.com/Lema1" target="_blank">
            @Lema1
          </a>
        </footer>
      </div>
    </Fragment>
  );
};

export default Layout;
